binary: Add tests for invalid inputs
* alphabetic characters at beginning, middle, end
* invalid digits

Test version is added (was previously unversioned)

Tested by ensuring that a solution that never errors gets a test
failure:

```
--- FAIL: TestParseBinary (0.00s)
        binary_test.go:50: ParseBinary(foo101) returned 5 and no error.  Expected an error.
```

Tested by ensuring that a solution that always errors gets a test
failure:

```
--- FAIL: TestParseBinary (0.00s)
        binary_test.go:46: ParseBinary(1) returned error "hard drive on fire, cannot convert to binary right now".  Error not expected.
```

Closes #271